# Generated by Django 3.2.7 on 2021-11-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciocliente', '0002_auto_20211119_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='soporte',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
