# Generated by Django 3.2.7 on 2021-11-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciocliente', '0003_soporte_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soporte',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
